### ISSUE TITLE
Add custom mode - Light / Dark

### ISSUE THREAD

**Issue by tusharnankani** [dheerajdlalwani/url-shortner#25]
- Add light mode.

This is not final but gives an idea how it might look like.

Just by adding a line of CSS, we can modify contrast here and there.

```css
* {
  filter: invert(1) hue-rotate(180deg);
}
```

![image](https://user-images.githubusercontent.com/61280281/118176701-641d7400-b44f-11eb-849c-fd06797c5284.png)
